kind: pipeline
name: non-production

steps:
# - restore-cache:
#   image: drillster/drone-volume-cache
#   restore: true
#   mount:
#     - ./.yarn-cache
#     - ./node_modules
#   volumes:
#     - /tmp/cache:/cache

- name: npm install
  image: node:14
  commands:
    - node -v
    - npm -v
    - npm install
    # - yarn --version
    # - yarn config set cache-folder .yarn-cache
    # - yarn install --pure-lockfile

- name: docker 
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: thibaultdct/portalz-api-node
    tags: latest

- name: deploy
  image: appleboy/drone-ssh
  environment:
    DB_URL:
      from_secret: DB_URL
    DB_USERNAME:
      from_secret: DB_USERNAME
    DB_PASSWORD:
      from_secret: DB_PASSWORD
    AUTH_SECRET:
      from_secret: AUTH_SECRET
  settings:
    host:
      from_secret: SSH_HOST
    username:
      from_secret: SSH_USERNAME
    password:
      from_secret: SSH_PASSWORD
    port: 22
    script:
    - sudo docker run --name=portalz -d -p 8081:8080 -e DB_URL=$DB_URL -e DB_USERNAME=$DB_USERNAME -e DB_PASSWORD=$DB_PASSWORD -e AUTH_SECRET=$AUTH_SECRET thibaultdct/portalz-api-node