kind: pipeline
name: non-production

steps:
- name: npm install
  image: node:14
  commands:
    - node -v
    - npm -v
    - npm install

- name: docker 
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: thibaultdct/portalz-api-node
    tags: latest

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: SSH_HOST
    username:
      from_secret: SSH_USERNAME
    password:
      from_secret: SSH_PASSWORD
    port: 22
    envs: [SSH_HOST, SSH_USERNAME, SSH_PASSWORD, DB_URL, DB_USERNAME, DB_PASSWORD]
    script:
    - echo "${DB_URL}"
    - sudo docker run --name=portalz -d -p 8081:8080 -e DB_URL=${DB_URL} -e DB_USERNAME=${DB_USERNAME} -e DB_PASSWORD=${DB_PASSWORD} -e AUTH_SECRET=${AUTH_SECRET} thibaultdct/portalz-api-node